config/routes.rb
Rails.application.routes.draw do
  resources :breastfeedings
  resources :babies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    has_many :breastfeedings, dependent: :destroy
    def total_quantity
        breastfeedings.sum(:quantity)
    end

    def breastfeedings_times_today
        breastfeedings.where("created_at > ?", Date.today).count
    end

    def last_breastfeeding_today_date
        breastfeedings.where("created_at > ?", Date.today).last.created_at
    end

    def breastfeeding_quantity_today
        breastfeedings.where("created_at > ?", Date.today).sum(:quantity)
    end

    def breastfeeding_time_today
        breastfeedings.where("created_at > ?", Date.today).sum(:feeding_time)
    end
end

app/models/breastfeeding.rb
class Breastfeeding < ApplicationRecord
    belongs_to :baby 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_params
      params.require(:baby).permit(:name, :age)
    end
end

app/controllers/breastfeedings_controller.rb
class BreastfeedingsController < ApplicationController
  before_action :set_breastfeeding, only: [:show, :edit, :update, :destroy]

  # GET /breastfeedings
  # GET /breastfeedings.json
  def index
    @breastfeedings = Breastfeeding.all
  end

  # GET /breastfeedings/1
  # GET /breastfeedings/1.json
  def show
  end

  # GET /breastfeedings/new
  def new
    @breastfeeding = Breastfeeding.new
    @babies = Baby.pluck :name, :id
  end

  # GET /breastfeedings/1/edit
  def edit
  end

  # POST /breastfeedings
  # POST /breastfeedings.json
  def create
    @breastfeeding = Breastfeeding.new(breastfeeding_params)

    respond_to do |format|
      if @breastfeeding.save!
        format.html { redirect_to @breastfeeding, notice: 'Breastfeeding was successfully created.' }
        format.json { render :show, status: :created, location: @breastfeeding }
      else
        format.html { render :new }
        format.json { render json: @breastfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breastfeedings/1
  # PATCH/PUT /breastfeedings/1.json
  def update
    respond_to do |format|
      if @breastfeeding.update(breastfeeding_params)
        format.html { redirect_to @breastfeeding, notice: 'Breastfeeding was successfully updated.' }
        format.json { render :show, status: :ok, location: @breastfeeding }
      else
        format.html { render :edit }
        format.json { render json: @breastfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breastfeedings/1
  # DELETE /breastfeedings/1.json
  def destroy
    @breastfeeding.destroy
    respond_to do |format|
      format.html { redirect_to breastfeedings_url, notice: 'Breastfeeding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breastfeeding
      @breastfeeding = Breastfeeding.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def breastfeeding_params
      params.require(:breastfeeding).permit(:quantity, :feeding_time, :baby_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/breastfeedings_helper.rb
module BreastfeedingsHelper
end

app/views/babies/_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% baby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/babies/edit.html.erb
<h1>Editing Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Show', @baby %> |
<%= link_to 'Back', babies_path %>

app/views/babies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Babies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Veces que ha tomado pecho</th>
      <th>Cantidad tomada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @babies.each do |baby| %>
      <tr>
        <td><%= baby.name %></td>
        <td><%= baby.age %></td>
        <td><%= baby.breastfeedings.count %></td>
        <td><%= baby.total_quantity %></td>
        <td><%= link_to 'Show', baby %></td>
        <td><%= link_to 'Edit', edit_baby_path(baby) %></td>
        <td><%= link_to 'Destroy', baby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby', new_baby_path %>

app/views/babies/new.html.erb
<h1>New Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Back', babies_path %>

app/views/babies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @baby.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @baby.age %>
</p>

<table>
  <thead>
    <tr>
      <th>Cuantas veces a tomado pecho hoy</th>
      <th>Ultima vez que tomo</th>
      <th>Cuanto tiempo ha tomado este dia</th>
      <th>Cantidad tomada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @baby.breastfeedings_times_today %></td>
      <td><%= @baby.last_breastfeeding_today_date %></td>
      <td><%= @baby.breastfeeding_quantity_today %></td>
      <td><%= @baby.breastfeeding_time_today %></td>
    </tr>
    
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_baby_path(@baby) %> |
<%= link_to 'Back', babies_path %>

app/views/breastfeedings/_form.html.erb
<%= form_with(model: breastfeeding, local: true) do |form| %>
  <% if breastfeeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breastfeeding.errors.count, "error") %> prohibited this breastfeeding from being saved:</h2>

      <ul>
      <% breastfeeding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :baby_id %>
    <%= form.select :baby_id, options_for_select(@babies) %>
  </div>

  <div class="field">
    <%= form.label :feeding_time %>
    <%= form.text_field :feeding_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/breastfeedings/edit.html.erb
<h1>Editing Breastfeeding</h1>

<%= render 'form', breastfeeding: @breastfeeding %>

<%= link_to 'Show', @breastfeeding %> |
<%= link_to 'Back', breastfeedings_path %>

app/views/breastfeedings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breastfeedings</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Feeding time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breastfeedings.each do |breastfeeding| %>
      <tr>
        <td><%= breastfeeding.quantity %></td>
        <td><%= breastfeeding.feeding_time %></td>
        <td><%= link_to 'Show', breastfeeding %></td>
        <td><%= link_to 'Edit', edit_breastfeeding_path(breastfeeding) %></td>
        <td><%= link_to 'Destroy', breastfeeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breastfeeding', new_breastfeeding_path %>

app/views/breastfeedings/new.html.erb
<h1>New Breastfeeding</h1>

<%= render 'form', breastfeeding: @breastfeeding %>

<%= link_to 'Back', breastfeedings_path %>

app/views/breastfeedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @breastfeeding.quantity %>
</p>

<p>
  <strong>Feeding time:</strong>
  <%= @breastfeeding.feeding_time %>
</p>

<%= link_to 'Edit', edit_breastfeeding_path(@breastfeeding) %> |
<%= link_to 'Back', breastfeedings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laesposadeapu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>